language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.0
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
jdk:
  - oraclejdk8
licenses:
  - '.+'
script: ./gradlew clean test
branches:
  except:
    - gh-pages
notifications:
  email: false
  rooms:
    - pitchedapps:G5OB9U1vsDxy9mxt0Nt6gbFu#kau
    on_success: always
    on_failure: always
sudo: false
cache:
  directories:
    - $HOME/.m2
before_script:
  - chmod +x gradlew