language: android
jdk:
- oraclejdk8
env:
  global:
  - ANDROID_API=28
  - EMULATOR_API=19
  - ANDROID_BUILD_TOOLS=28.0.3
git:
  depth: 500
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
#  - android-$EMULATOR_API
  - extra-android-m2repository
  - extra-google-m2repository
#  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
#  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  licenses:
  - ".+"
#before_script:
#- echo "y" | android update sdk -a --no-ui --filter android-$EMULATOR_API
#- echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$EMULATOR_API
#- android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}' # list all targets
#- echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
#- emulator -avd test -skin -no-audio -no-window &
#- android-wait-for-emulator
#- adb shell settings put global window_animation_scale 0 &
#- adb shell settings put global transition_animation_scale 0 &
#- adb shell settings put global animator_duration_scale 0 &
#- adb shell input keyevent 82 &
script:
- chmod +x gradlew
- "./gradlew --quiet androidGitVersion"
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./gradlew lintRelease publishRelease; else ./gradlew lintRelease test; fi
branches:
  except:
  - gh-pages
  - l10n_dev
notifications:
  email: false
  slack:
    rooms:
    - pitchedapps:G5OB9U1vsDxy9mxt0Nt6gbFu#kau
    on_success: always
    on_failure: always
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
before_install:
- yes | sdkmanager "platforms;android-$ANDROID_API"
- openssl aes-256-cbc -K $encrypted_12e8842891a3_key -iv $encrypted_12e8842891a3_iv
  -in files/kau.tar.enc -out kau.tar -d
- tar xvf kau.tar