language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.0
  - android-26
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - ".+"
script:
- ./gradlew --quiet androidGitVersion
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./gradlew lintRelease publishRelease; else ./gradlew lintRelease test; fi
branches:
  except:
  - gh-pages
notifications:
  email: false
  slack:
    rooms:
    - pitchedapps:G5OB9U1vsDxy9mxt0Nt6gbFu#kau
    on_success: always
    on_failure: always
sudo: false
cache:
  directories:
  - "$HOME/.m2"
before_script:
- chmod +x gradlew
before_install:
- openssl aes-256-cbc -K $encrypted_12e8842891a3_key -iv $encrypted_12e8842891a3_iv
  -in files/kau.tar.enc -out kau.tar -d
