language: android
jdk:
- oraclejdk11
env:
  global:
  - ANDROID_API=29
  - EMULATOR_API=19
  - ANDROID_BUILD_TOOLS=29.0.2
git:
  depth: 500
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - ".+"
script:
- chmod +x gradlew
- "./gradlew --quiet androidGitVersion"
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./gradlew spotlessCheck lintRelease publishRelease;
  else ./gradlew spotlessCheck lintRelease testReleaseUnitTest; fi
branches:
  except:
  - gh-pages
  - l10n_dev
notifications:
  email: false
  slack:
    rooms:
      secure: kt/n/Mn7qbRKg6OXFLY2oxon9mjdrowuGnOavGTsXr7OQDKNp/PMSanIhxYJwkU8at5jO2Zlyjh/orksBGy6ERX4+AMbTWlDH0n/F5E7hHwxDABBup78VgU+pBgbdUrF5taUkrODcl3ytP3Pwx5MfSrdw5v6IKR0P00Tpwo0paeurBDp9XnG2DhOn3diJNH1YpdHuIKoPnLORFnUkTAWdGqQkfQFY64idbD9JO+/KODG7Y1KDtrWgg4x8FrOLAaVRQddISxyBpOoCiThF3k8nbQztAwhDyJWber0xWNuTwlKKfTFQvxkUkjb55jxRePFQTmgw/u+ip/fnBfVx9l/BAc1Rj2vRVRoAWfmWaBRQU05lZHeI4tvuuBmBxhT2qHeexdXYxPOugFHrlG34u6m1ZiSOQ5mcOxmMFaK2wjonL6haTqN5Uzm7ZX3y6LzIihZi5SzOAnfjUzGpEkw3uh+h7tNRXNpu4uk//GTd2gO/CHlIr+6Hm70RihN32ns5++EmbyP3rJ/6Xwk1tYJMRIJWpU+8kdadm9DZmsB1TPb/u9Zjdaq2pdkcyP5huZvZIdcPjiCkAiSuwtF+pxjd5Ygch7U/W/H73zDwo7dKknt40DOdv+1oiPstiaoDCgLvWiMDaszG15YKlTx8ggbxbLZZapriOc2u9F/XmQwNiZmqMo=
    on_success: always
    on_failure: always
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_install:
- yes | sdkmanager "platforms;android-$ANDROID_API"
- openssl aes-256-cbc -K $encrypted_12e8842891a3_key -iv $encrypted_12e8842891a3_iv
  -in files/kau.tar.enc -out kau.tar -d
- tar xvf kau.tar
